name          'tlcowling-tomcat'
version       '0.1.0'
source        'https://github.com/tlcowling/tlcowling-tomcat.git'
author        'Tom Cowling <tom.cowling@gmail.com>'
license       'MIT'
summary       'Puppet module to install and configure Apache Tomcat'
description   ''
project_page  'https://github.com/tlcowling/tlcowling-tomcat'

dependency 'puppetlabs/stdlib'
